apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3
        ports:
          - containerPort: 7000
            name: intra-node
          - containerPort: 7001
            name: tls-intra-node
          - containerPort: 7199
            name: jmx
          - containerPort: 9042
            name: cql
        env:
          - name: CASSANDRA_SEEDS
            value: cassandra-0.cassandra,cassandra-1.cassandra,cassandra-2.cassandra
          - name: MAX_HEAP_SIZE 
            value: 8000M
          - name: HEAP_NEWSIZE
            value: 4096M
          - name: CASSANDRA_CLUSTER_NAME
            value: "Cassandra-K8S"
          - name: CASSANDRA_DC
            value: "K8S"
          - name: CASSANDRA_RACK
            value: "Cluster-01"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"            
          - name: CASSANDRA_ENDPOINT_SNITCH
            value: GossipingPropertyFileSnitch
            # http://cassandra.apache.org/doc/4.0/configuration/cassandra_config_file.html?highlight=endpoint_snitch
        resources:
          requests:
            memory: "4200Mi"
            cpu: "2000m"
          limits:
            memory: "8400Mi"
            cpu: "4000m"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
      annotations:
        volume.beta.kubernetes.io/storage-class: longhorn
      labels:
         app: cassandra
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi